version: '3'

services: 
  haproxy:
    image: haproxy
    ports: 
      - "4000:4000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  webnode1:
    image: webnode
    ports:
      - "1111:4000"
    environment: 
      - APPID=1111
  webnode2:
    image: webnode
    ports:
      - "2222:4000"
    environment: 
      - APPID=2222
  webnode3:
    image: webnode
    ports:
      - "3333:4000"
    environment: 
      - APPID=3333
  webnode4:
    image: webnode
    ports:
      - "4444:4000"
    environment: 
      - APPID=4444